
### Fixed

- Running `neat.to.cdf.data_model()` no longer gives a
`UnboundLocalError` if there is an error in the deployment.